### ISSUE TITLE
Fix Avenger backlog email generation

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/cadet#1040]
Following the fix in #1031, it is now broken. See linked PR's description for details on rationale and proposed fix.

**Comment by RichDom2185** [comment]
Part of #1032 (but kept as separate issue due to high priority (feature broken, as opposed to a memo to fix).

**Comment by GabrielCWT** [comment]
I have confirmed that PR #1065 has resolved this issue.

**Comment by RichDom2185** [comment]
> I have confirmed that PR #1065 has resolved this issue.

Ok, will close this issue.
