### ISSUE TITLE
Deploy Artifacts from Travis to S3

### ISSUE THREAD

**Issue by evansb** [source-academy/cadet#13]

**Comment by ningyuansg** [comment]
@evansb Can you elaborate on what are 'artifacts'?

**Comment by evansb** [comment]
Deployment artifacts, i.e tarball of erlang bytecodes (if you are still doing that)

**Comment by ningyuansg** [comment]
Oh, I see. We're pretty far off from there. Still manually building the deployment package and sending it to the ec2 instances right now.

**Comment by angelsl** [comment]
This is done now, using GitHub Actions.
