### ISSUE TITLE
Associating XP with assessment components

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#130]
In order to "gamify" the Academy, we would need to have the concept of "eXperience Points", associated with assessment components.

Are we intending to go down this route?

**Comment by ningyuansg** [comment]
Where will the information about how XP and grades are given come from? 

Ideally, I think that they should be in the assessments XML files, so that we don't need to look at more than one location to find this information, but the XML files currently do not hold this information.

**Comment by martin-henz** [comment]
Yes, I think the assessment XML files are the correct place for this info. The publish and due dates are already there. (Any suggestion for a format is welcome. I'll input the data.

**Comment by ningyuansg** [comment]
This should be handled together with #142 then, since that's regarding the parsing of said XML.

**Comment by indocomsoft** [comment]
Fixed by b2fb633e0b697125f27435600ff17eb33184ee16
