### ISSUE TITLE
Property library for question with type multiple_choice is null

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#136]
On GET `/assessments/{assessmentId}`,

```json
{
  "type": "mission",
  "title": "Do you think I am easier to be played on than a pipe?",
  "questions": [
    {
      ...
    },
    {
      "type": "multiple_choice",
      "library": null,
      "id": 16,
      "content": "Oddish",
      "choices": [
        {
          "id": 0,
          "hint": "Santalune City",
          "content": "Charmeleon"
        },
        {
          "id": 1,
          "hint": "Nuvema Town",
          "content": "Rapidash"
        },
        {
          "id": 2,
          "hint": "Striaton City",
          "content": "Staryu"
        }
      ],
      "answer": null
    },
    {
      ...
    },
  ],
  "missionPDF": null,
  "longSummary": "O Romeo, Romeo! wherefore art thou Romeo?.",
  "id": 3
}
```

1. Property type should be `mcq`, not `multiple_choice`.
2. Property library should not be `null` (expected a number).

**Comment by tuesmiddt** [comment]
I can change the property type.

Why should library not be null?

**Comment by ningyuansg** [comment]
Thanks. We provide an interpreter on the side for MCQ questions, so we need information on what lib to load into it.

**Comment by tuesmiddt** [comment]
Does every MCQ question have an interpreter? Currently 'library' is an optional field.

**Comment by ningyuansg** [comment]
Yep, so library should be a required field. We could've just set a library per assessment instead of question, but wanted to open up the flexibility for different questions within an assessment to load different libraries.

**Comment by tuesmiddt** [comment]
OK. Will make the necessary changes. Wasn't aware that every mcq question must have a library. I thought some could be just plain english questions.
