### ISSUE TITLE
Parse assessment XML files into the database

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#142]
This is a key and potentially time-consuming part of the assessment toolchain.

1. Clone the cs1101s git repository locally
2. **Parse the XML files representing assessments (missions, quests, contests, paths), and save them into the database**
4. Send assessments saved in the database to the frontend

Most of these are OK, but step (2) is untouched. I think it's pretty important.

**Comment by indocomsoft** [comment]
https://github.com/kbrw/sweet_xml looks good

**Comment by ningyuansg** [comment]
Sweet XML is already being used by some ExAws module (can't remember which or if I added it already).

**Comment by ningyuansg** [comment]
We also need to add a field to the assessments to track their order (because the built-in ID is based on insertion order and can't easily be mapped to which story should be shown to the user in the game). I'll elaborate on this on another issue a bit later, sorry if it's vague.

**Comment by martin-henz** [comment]
We currently have two places already where we process XML: 
* The textbook toolchain uses Ruby-on-Rails for generating HTML from the XML textbook sources.
* The assessment processing toolchain in the bitbucket repository has several pathways:
** XML -> MD -> PDF
** XML -> LaTeX -> PDF
** XML -> webpage (html and js files) -> ZIP file

In the source-academy-2, I guess we just uploaded the generated MD files to the Source Academy server? In any case, you may want to take a look at the bitbucket repo to see what's the current functionality.

If you like, we could add what's needed to the XML processing tools in the bitbucket repo. For example, let me know if you would like me to generate a JSON file with the assessment details, including deployment dates, due dates, marks, XP, dependencies etc.

**Comment by ningyuansg** [comment]
I looked at the xsl for generating *.mission files from the source XML files, and I don't think we can reuse them. It looks as though they were generated specifically for use in [source-academy2](https://github.com/source-academy/source-academy2). 

I see two ways of doing this:
1. Parse the XML files that were locally cloned into the database, being represented by an assessment model
2. Define a xslt transformation to create a JSON that exactly fits what the backend sends to frontend. Backend saves that JSON and 'dumbly' sends it to the frontend.

I'm leaning towards (1), since we eventually need to extract the graderPrograms from the XML anyways, which means parsing the assessments is inevitable. The graderPrograms are the thing that the [grader](https://github.com/source-academy/grader) uses to grade the student's programs.

Ultimately, implementation is up to the backend team though.

**Comment by martin-henz** [comment]
The authors of the XML files for assessments would need to check that their XML files are in good shape. So we will have some XML processing in any case in the context of the CS1101S bitbucket toolchain that the avengers are exposed to. For example: XML -> MD -> PDF. (Should the assessment PDF files be in IVLE, too?)

To that's where the Avenger's work stops, right? Then the backend somehow picks up the XML files and processes them, according to your preferred Way 1.

I'm ok with this. Just need to make sure we have a clear workflow in place for the Avenger teams.

**Comment by ningyuansg** [comment]
@indocomsoft I'll write out a draft API for the XML files by today.

**Comment by indocomsoft** [comment]
@ningyuansg  Alright thanks!
