### ISSUE TITLE
Assessments need additional property/field to map to a story in the game

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#148]
The game comes in two modes,

1. An open-world mode, where the user can explore the spaceship and talk to NPCs with no restrictions
2. A scripted mode ('*story*'), where the user is guided through conversations with specific NPCs in specific locations

There are many stories, most ending in a link that goes to a certain assessment. Therefore, each story maps to a certain assessment. In #84, we added the capability to ignore stories mapping to assessments that have been attempted. If all stories are ignored, the open-world mode is rendered for the user.

---

The problem now is that we don't have a way to map a story to an assessment. The current `id` field of an assessment is only it's insertion order into the database. Consider the following functions from [source-academy](https://github.com/source-academy/source-academy2/blob/11466e86facfdcb3527731af0e914baa1da845ef/lib/source_academy/assessments.ex#L642),

```elixir
  def prepare_game(student) do
    # Get all non-attempted assessment
    assessments = Repo.all(
      from a in Assessment,
        left_join: s in Submission,
          on: a.id == s.assessment_id and s.student_id == ^student.id,
        where: is_nil(s.student_id),
        select: a
    )
    # Filter those can be attempted, min by order, mission first
    assessments =
      assessments
      |> Enum.filter(&(&1.type != :path && can_attempt?(&1, student.user)))
    if Enum.empty?(assessments) do
      nil
    else
      [hd | _ ] = Enum.sort_by(assessments,
        &story_name_pair/1,
        &compare_story_name_pair/2)
      hd
    end
  end

  def story_name_pair(assessment) do
    {assessment.type, assessment.name}
  end

  def compare_story_name_pair({t1, n1}, {t2, n2}) do
    cond do
      t1 == t2 -> n1 <= n2
      t1 == :mission -> true
      t1 == :sidequest && t2 == :mission -> false
      t1 == :contest && t2 == :mission -> false
      t1 == :contest && t2 == :sidequest -> false
      true -> false
    end
  end

  def story_name(assessment) do
    type = Atom.to_string(assessment.type)
    String.downcase(type) <> "-" <> assessment.name
  end
```

In the above, assessments are sorted according to the comparison in `compare_story_name_pair/2` and filtered at `prepare_game/1` student. A corresponding string representing the story to show in the game is then generated using `story_name/1`. 

The 'story_names' all correspond to the filename of an XML file from `./stories/` in the cs1101s repository. We pass a *'story_name'* to the javascript function starting the game, and it will fetch the appropriate XML file and assets from AWS S3, and load them up for the user ([the JS function](https://github.com/source-academy/cadet-frontend/blob/97268b8d14bd0249ff98f6dd6e3cbe8215296917/src/components/academy/game/create-initializer.js#L72)).

---

Overall, two problems to solve:

- There is a need for an addition property/field, perhaps *'story_name'*, which can be compared, and sorted just like in source-academy2 to determine the load order of stories
    - This new property, representing which story to load should then be added to the `/user` endpoint
- Since there is a change in the names of missions in the cs1101s repository, there is a need to either:
    - Rename the story XML files in a similar fashion, or 
    - Transform the new mission filenames to current story XML filenames when sending it to the frontend

**Comment by tuesmiddt** [comment]
Just wanna clarify some things:
1. Assessments may or may not belong to a story.
2. User may or may not have one current story

Is my understanding correct?

**Comment by tuesmiddt** [comment]
@ningyuansg

**Comment by ningyuansg** [comment]
Yes, both are optional

**Comment by tuesmiddt** [comment]
@ningyuansg 
I looked at the cs1101s repo. It looks like there's an (optional) one-one mapping between stories and assessments. 

In #84, you mentioned this:
> The story act corresponding to the assessment in the array of not yet attempted/done assessments with the earliest open_at time is shown. If none, show the open-world spaceship.
I presume this is the story you are asking for in the `/user` endpoint. Should certain assessment classes (Contest/Sidequest) be excluded from this?

**Comment by ningyuansg** [comment]
Yes, the user endpoint would be good. I'll refer to prof @martin-henz if we should show the students the game story even for contests and quests.

**Comment by martin-henz** [comment]
If I remember right, we discussed that there should be a way to escape the story at any point, and go straight to the assessment. In that case: Yes, we should show a story whenever we have one.
