### ISSUE TITLE
Redefining Library

### ISSUE THREAD

**Issue by remo5000** [source-academy/cadet#149]
Recently, I've implemented the external libraries on the frontend, and in doing so understood a bit more about how the interpreter uses the external libraries. As such, a slight change in the structure of the `Library` (under `Question`) is required.

Right now the structure is [as such](https://github.com/source-academy/cadet-frontend/blob/97268b8d14bd0249ff98f6dd6e3cbe8215296917/src/components/assessment/assessmentShape.ts#L66).
- `chapter`
- `externals` is a list of strings that expose global functions to the interpreter (such as `show`, that renders a rune onto a webGL object).
- `files` is a list of strings used to load up libraries. This is not needed anymore as the website is static, meaning that all the libraries must be served initially and used when it is needed.
- `globals` is a list of strings. It has been unused so far, but I misinterpreted its usage before. Updated the usage below.

This is a structure that would [better](https://github.com/source-academy/cadet-frontend/blob/92a14499e3638ccbaa1bd16ad5e7363c7566a809/src/components/assessment/assessmentShape.ts) suit the needs of the website:
Library:
 -  `chapter: number` (no change)
  - `externalLibraryName: "NONE" | "TWO_DIM_RUNES" | "THREE_DIM_RUNES" | "CURVES" | "SOUND"`. This will be used to specify what external library (rendering webGL or playing sound) the assessment would be using. I considered inferring this from `externals`, but a field is more explicit and leaves no room for error on our part.
  - `externals: string[]` (no change)
  - `globals: <string, value>[]`. This is a list of pairs (`string`, `value`) that can be used to specify constants. This will be useful for the staff to introduce default values for the students or external libraries.

Do let me know if there are issues regarding data representation, @ningyuansg @indocomsoft @tuesmiddt

**Comment by ningyuansg** [comment]
@remo5000 Can you look at the assessment files at cs1101s repository and see what node and attributes map to what library properties here so the backend team can have an easier time parsing the XML (#142)?

**Comment by remo5000** [comment]
@ningyuansg sure

**Comment by remo5000** [comment]
@tuesmiddt I've mocked the API calls [here](https://github.com/source-academy/cadet-frontend/blob/92a14499e3638ccbaa1bd16ad5e7363c7566a809/src/mocks/assessmentAPI.ts#L83).

**Comment by tuesmiddt** [comment]
I'm assuming given this:
```
[
    ExternalLibraryNames.CURVES,
    [
      'make_point',
      'draw_points_on',
      'draw_connected',
      'draw_points_squeezed_to_window',
      'draw_connected_squeezed_to_window',
      'draw_connected_full_view',
      'draw_connected_full_view_proportional',
      'x_of',
      'y_of',
      'unit_line',
      'unit_line_at',
      'unit_circle',
      'connect_rigidly',
      'connect_ends',
      'put_in_standard_position',
      'full_view_proportional',
      'squeeze_full_view',
      'squeeze_rectangular_portion'
    ]
  ]
```
`externalLibraryName` = `ExternalLibraryNames.CURVES` and `externals` can be any subset of the inner array?

**Comment by remo5000** [comment]
@tuesmiddt yes, except the array of strings and the `externalLibraryName` are different properties in the `Library` object. Nesting like that looks good though, we can change the structure to:

Library:
- chapter
- external:
  - externalLibraryName (string, one of the constants)
  - exposedSymbols (array of strings)
- globals

What do you think?

**Comment by tuesmiddt** [comment]
@remo5000 Sounds good. Let's go with this.

**Comment by remo5000** [comment]
Sure, I'll update the frontend PR with this revised structure to confirm

**Comment by tuesmiddt** [comment]
@remo5000 I'll be returning `name` instead of `externalLibraryName`

**Comment by ningyuansg** [comment]
Renaming exposedSymbols -> naming also fits well with the [proposed assessments XML API](https://gist.github.com/ningyuansg/edc8918a1f52bfd907c4a4e305545107#external)
