### ISSUE TITLE
Studios and Reflections should be "assessments"

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#160]
The Avengers of Studios and Instructors of Reflections need to take attendance after the Studios and Reflections. A uniform way of doing so could be to assign a grade of 1 to each Studio and Reflection session, and then allow the Avengers/Instructors to use the "grade moderation" feature in order to manually record that a student was absent.

**Comment by remo5000** [comment]
Sounds good, we can easily make them Paths

**Comment by martin-henz** [comment]
We have used a google sheet for this and it gets the job done.
