### ISSUE TITLE
XP system taking shape

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#175]
Folks, Eldric has been working on an XP system, and it's looking good. There will be one more round of feedback from Avengers, but you can a look already right now to see if there are concerns from the point of view of implementation. Academy Developers: To see the document, look for my post in Slack "general" from 30/7/2018.

**Comment by indocomsoft** [comment]
Fixed by b2fb633e0b697125f27435600ff17eb33184ee16
