### ISSUE TITLE
Upgrade to Elixir 1.7

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#189]

**Comment by jiachen247** [comment]
note that one dependency fails to compile once upgraded to Elixir 1.7

https://github.com/meh/exquisite/issues/10

**Comment by jiachen247** [comment]
https://github.com/getsentry/sentry-elixir/pull/309

New version of sentry which does not log NoRouteFound depends on elixir 1.7

To plan for upgrade asap.

**Comment by jiachen247** [comment]
#343
