### ISSUE TITLE
Reaffirm Architecture Decision

### ISSUE THREAD

**Issue by evansb** [source-academy/cadet#19]
Since we have 2 full time frontend engineers and 2 part time + 1 full time backend engineers, I think it makes more sense to make the frontend a single page application, and having the backend engineers write a RESTful API instead of server rendered.

We will disucss this in the first sprint meeting.

**Comment by indocomsoft** [comment]
Decided to separate front-end to https://github.com/source-academy/cadet-frontend as SPA
