### ISSUE TITLE
GET /user should send max grade

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#205]
The max grade sent by `GET /user` should be the total maximum grade achievable by that particular user (i.e. the max grade of all submitted assessments by that user), and will be used in conjunction with the already implemented grade field of `GET /user` to render a grade progress bar for the user in the frontend.

**Comment by indocomsoft** [comment]
Only submitted and not open assessments right?

**Comment by ningyuansg** [comment]
Yep
