### ISSUE TITLE
Refactor Authorization

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#246]
As briefly mentioned in #243

**Comment by jiachen247** [comment]
This would be quite a big refractor.

**Comment by martin-henz** [comment]
postponed

**Comment by angelsl** [comment]
I just looked at the discussion in #243 and it didn't seem like it was a problem in the past semester&mdash;we don't have rogue TAs that go around editing other submissions.

So I'm going to close this.

**Comment by martin-henz** [comment]
Yes, I agree.
