### ISSUE TITLE
/grading should return the grader, if any.

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet#260]
The grader is the staff member who approves the grade.

This will allow front end to determine if the problem/mission has already been graded.

Simultaneously, there should be an endpoint to "confirm" the grading (i.e. for acknowledging autograding).

Recommend implementation by adding a user_id column to the table.

**Comment by jiachen247** [comment]
I propose adding grader_id to submission table.

Additionally, we can work with the frontend team to reflect that submission has been graded by a staff.

Note that avengers will have to go into the grading page and click save regardless of if any adjustments were made to the grade and xp.
