### ISSUE TITLE
Unsubmit support

### ISSUE THREAD

**Issue by blackening** [source-academy/cadet#271]
There may be legitimate reasons to unsubmit an assignment.

**Comment by jiachen247** [comment]
@martin-henz is this feature request approved?

**Comment by martin-henz** [comment]
Yes, it's approved, provided that we have an audit trail. 

Let us limit the feature as follows:
Only the student's Avenger can unsubmit the submission.

That means as audit trail, we only need one flag: unsubmit_happened 

Then we can use the usual filter functions in the missions and see for what missions/avengers/students etc unsubmit has been used.

**Comment by martin-henz** [comment]
Will be resolved by: https://github.com/source-academy/cadet/pull/312
