### ISSUE TITLE
IVLE is being deprecated next semester

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#337]
Our only log in solution is using ivle right now.

There are 2 possible solutions that I see:
1. Add a new way of logging in using username and password. This will require a non-trivial amount of effort
2. I have created a library in elixir to connect to luminus which could perhaps be used in place of the IVLE authorization method. However, it is based on reverse engineering their angular frontend -- they have been postponing the release of their public API since March 2018. There is a non-zero probability that this API will change some time in the future. The library is located at https://github.com/indocomsoft/fluminus

**Comment by martin-henz** [comment]
OK, let me check with the Luminus people.

**Comment by martin-henz** [comment]
Got a response from LumiNUS staff. They pointed out that LumiNUS has a "more completed API set", which is documented here: https://luminus.portal.azure-api.net/

**Comment by jiachen247** [comment]
Looking around the API documentation there dosent seem to be an API for authentication. The ios app for luminus does use web an oauth style web login so I believe there is one but its just not currently documented. Would love more info on this!

**Comment by martin-henz** [comment]
Sorry, you weren't in the loop, @jiachen247 . Here is the prelim documentation that I received from the LumiNUS team.
[How to use the API.pdf](https://github.com/source-academy/cadet/files/2900474/How.to.use.the.API.pdf)
[How do I start.pdf](https://github.com/source-academy/cadet/files/2900475/How.do.I.start.pdf)
