### ISSUE TITLE
CS1101S is hardcoded into the auth check

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet#383]
The `CS1101S` module code is currently hard coded in the ivle/luminus checks.

This tightly couples cadet to cs1101s. In addition, prof @martin-henz  has assigned us a staging module for us to play around with. I propose moving the module code into general config to make the backend more extensible.

to add this to deployment handbook as well.

**Comment by martin-henz** [comment]
Yes, this is crucial, not just for testing: I'll be teaching a summer workshop module called 
SWS3012 Computational Pearls with Functional Programming
where we cover the functional programming subset of CS1101S. We will (of course) use the Source Academy, and the module is already created in LumiNUS.

**Comment by jiachen247** [comment]
Closed with #384
