### ISSUE TITLE
From 2018 team post-mortem: Can create an admin frontend to manage the backend using these API

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#411]
- Right now everything(?) works off an API, which is good

*Note from Martin:* I feel that a simple admin frontend would improve the system a lot. We had a hard time getting a hold of developers for small changes such as:
* wrong release and submission date of missions
* wrong picture
* small errors in missions

The principle of taking the missions/paths/quests from the private module content repo (currently bitbucket: CS1101S) is I think good, because it allows us to make use of git for peer review of changes. I'm not sure if it is wise to automatically grab the content from the repo at (currently) hourly intervals. It may be better to explicitly trigger the grabbing of the content from the private repo. Such explicit triggering could be a feature of the admin frontend. Any views on this?

**Comment by angelsl** [comment]
Done with #586.
