### ISSUE TITLE
From 2018 team post-mortem: Mission editing

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#412]
- Currently inconvenient to make changes to the mission after it’s published
- e.g. Cannot easily change due date

*Note from Martin:* strongly agree. This would be one of the central features of an admin interface.

**Comment by geshuming** [comment]
This is still an issue, but more relevant to backend

**Comment by martin-henz** [comment]
This is handled by the Mission Control tool, currently available at:
https://sourceacademy.nus.edu.sg/mission-control
