### ISSUE TITLE
Pulling assessments and stories from bitbucket: Need to visit all folders

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#416]
Currently, only dedicated folders are visited: "missions", "paths" etc. We decided to simplify this and pull assessments from all folders in the bitbucket repos.

Same with stories: Currently there is one folder "xml", but there is no need to hard-wire that. Best pull from all folders in the repo.

**Comment by angelsl** [comment]
Obsolete since we are moving away from importing assessments from Git.
