### ISSUE TITLE
URLs in share feature are too long

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#417]
Currently, the "share" feature of the frontend encodes the entire program in the generated URL, which leads to very long URLs when the program gets long. 

An improvement would be:
"share" sends the program to the Source Academy server, which generates a hash key and stores the program in the database under that key. 
Any URL that includes such a hash key will retrieve the program from the database and sends it to the browser.

**Comment by angelsl** [comment]
Done with https://github.com/source-academy/cadet-frontend/pull/1130.
