### ISSUE TITLE
Avenger grading turnaround overview

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#421]
Avenger grading turnaround is crucial. Timely feedback on submitted assignments is known to correlated to achievement of learning outcomes.

If all staff see everyones average turnaround time, peer pressure tends to encourage quick turnaround.

What is the easiest way to achieve this in the Source Academy.

**Comment by angelsl** [comment]
Do we want this?

We have the dashboard now, so this will just be an extra column there.

**Comment by martin-henz** [comment]
Yes, the staff dashboard is a starting point. Once people use it, we will get a clearer picture how to tweak it next time.
