### ISSUE TITLE
SWS3012 Missions not updating from repo

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet#422]
Start and end times were updated on bitbucket and pull down to ec2b but never made it to the database. According to prof henz this was not the case last sem. To do root cause analysis to find out what caused this!

**Comment by martin-henz** [comment]
Fixed by https://github.com/source-academy/cadet/pull/423

**Comment by jiachen247** [comment]
@chrisjwelly thanks haha

**Comment by martin-henz** [comment]
Note that this is fixed by https://github.com/source-academy/cadet/pull/423
which is merged AND already deployed in the current cadet backend.
