### ISSUE TITLE
Proposal: Avengers should be able to submit their own answers

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet#432]
Title

**Comment by martin-henz** [comment]
See also: https://github.com/source-academy/cadet-frontend/issues/731

**Comment by angelsl** [comment]
Do we want this?

**Comment by martin-henz** [comment]
See discussion here: https://github.com/source-academy/cadet-frontend/issues/731

Ideally, staff should be able to submit and receive the result of autograding, before the mission is published. That way I can test the whole workflow, including autograding. We did have discrepancies between the results of test cases in browser vs AWS lambda. This would let us see the whole thing.

I do realize the issue with data contamination: the staff submissions need to be taken out of the avenger grading process and any statistics. But I think this is worth it.

**Comment by angelsl** [comment]
This is possible now.
