### ISSUE TITLE
Proposal: Use Bitbucket POST service to trigger import of assessments

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet#433]
Title.

https://confluence.atlassian.com/bitbucket/post-service-management-223216518.html

**Comment by jiachen247** [comment]
See https://github.com/source-academy/cadet/issues/385
Once we have the endpoint we can set the webhook to point to it!

**Comment by jiachen247** [comment]
https://confluence.atlassian.com/bitbucket/manage-webhooks-735643732.html#Managewebhooks-create_webhook

**Comment by jiachen247** [comment]
We will need to architecture our cloud platefrom abit tho

I suggest adding an auto scaling group +  a dedicated t2 micro instance to handle updates to assessment with an SG that only allows request from bitbucket.

That we we scale better and its just alot cleaner.

**Comment by angelsl** [comment]
Obsolete since we are moving away from importing assessments from Git.
