### ISSUE TITLE
Mutating Open Assessments

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet#435]
Currently, missions that are open are no longer updated when the updater run. Im guessing this rule was created to ensure that missions are not mutated after it is open.

However, over the last sems, mistakes with missions do happen and when they do they are labeled with the OBSOLETE in the title and a new one is created in place.

This creates some issues. Its confusing for students keeping track of the right assessments and two it makes it impossible to track progress cause the number of missions keep increasing. See https://github.com/source-academy/cadet/issues/129

To solve this, I propose we make the check a little smarter. I suggest we allow alterations to open missions provided no questions are added or removed. (This messes with the foreign keys).

**Comment by martin-henz** [comment]
This would be a huge improvement. We could remove typos, or add clarifications.

**Comment by martin-henz** [comment]
Addressed by https://github.com/source-academy/cadet/pull/458

**Comment by angelsl** [comment]
This is now possible with #258
