### ISSUE TITLE
Autograding should not alter manual grading

### ISSUE THREAD

**Issue by geshuming** [source-academy/cadet#436]
https://github.com/source-academy/cadet/blob/5980abb53642795c4da463903070aee83e4265ce/lib/cadet/jobs/autograder/result_store_worker.ex#L60

**Comment by jiachen247** [comment]
During SWS3012, there was an edge case mission closed at 2359. Avengers were really on the ball and started grading immediately. And then at 3AM the auto grader job was scheduled.

This autograder job then went ahead and overwrote the grade and adjustment.
