### ISSUE TITLE
Relax repo parsing rules

### ISSUE THREAD

**Issue by jiachen247** [source-academy/cadet#460]
currently only the these locations are being parsed.

`@locations %{mission: "missions", sidequest: "quests", path: "paths", contest: "contests"}`

I think we want to relax the rules a little so all folders within the assessment repo are searched for *.xml files.

**Comment by martin-henz** [comment]
> currently only the these locations are being parsed.
> 
> `@locations %{mission: "missions", sidequest: "quests", path: "paths", contest: "contests"}`
> 
> I think we want to relax the rules a little so all folders within the assessment repo are searched for *.xml files.

Yes, the addition of the "practical" folder may be a good time to implement this: Instead of hard-wiring "practical" (with or without "s"), you might just change the policy so that all folders are searched for .xml files. It may be more manageable, if we do this only in a flat structure. That way, we can add meta-information, or---who knows---some staging folders, without disturbing the live system.

**Comment by jiachen247** [comment]
@martin-henz  I feel like this might be a little confusing. The most flexible and the most straight forward one would be to traverse the repo recursively and parse *ALL* files! That way how we choose the manage the files is really up to the teaching team. To me all files in this repo should be read for prod. Trying to distinguish which files should be parsed and which not adds an layer of unnecessary complexity. (We can always add a max depth in case anyone is worried about security)

**Comment by martin-henz** [comment]
> @martin-henz I feel like this might be a little confusing. The most flexible and the most straight forward one would be to traverse the repo recursively and parse _ALL_ files! That way how we choose the manage the files is really up to the teaching team. To me all files in this repo should be read for prod. Trying to distinguish which files should be parsed and which not adds an layer of unnecessary complexity. (We can always add a max depth in case anyone is worried about security)

I agree. Would you look for particular file extensions, such as *.xml?
