### ISSUE TITLE
Production backend config drops HTTP status text

### ISSUE THREAD

**Issue by Aulud** [source-academy/cadet#479]
## [Bug] Production backend config drops HTTP status text
This bug does not occur in the development environment when using the `cors-proxy` script.

### Bug description
PRs https://github.com/source-academy/cadet/pull/474 and https://github.com/source-academy/cadet-frontend/pull/880 on the frontend prevents staff from submitting gradings on unfinished submissions, displaying a warning notification instead. When the backend receives a grading on an unfinished assessment, it returns the HTTP status code 405 (`Method Not Allowed`).

When the response is received by the frontend, the async handler `handleErrorResponse` is invoked,

    export function* handleResponseError(resp: Response | null) { 
      if (!resp) { 
        yield call(showWarningMessage, "Couldn't reach our servers. Are you online?"); 
        return; 
      } 
     
      let errorMessage: string; 
      switch (resp.status) { 
        case 401: 
          errorMessage = 'Session expired. Please login again.'; 
          break; 
        default: 
          errorMessage = `Error ${resp.status}: ${resp.statusText}`; 
          break; 
      } 
      yield call(showWarningMessage, errorMessage); 
    }

which, in the development environment, correctly shows the intended warning message

![Present HTTP status message on frontend](https://user-images.githubusercontent.com/44989315/63635697-f1c39980-c697-11e9-892a-407acc1a9948.png)

However, in the production environment, it appears the `statusText` has been dropped, resulting in the warning notification being unhelpful to the user,

![Missing HTTP status message on frontend](https://user-images.githubusercontent.com/44989315/63635708-32bbae00-c698-11e9-9e6a-9a5903fc9f3a.png)

Inspection of the returned response in the browser console confirms that whilst the same response (the string `Submission is not submitted yet.`) is returned in both environments, the 'statusText` is missing,

![HTTP response comparison](https://user-images.githubusercontent.com/44989315/63635830-b4600b80-c699-11e9-8755-f2ab56c84bd5.png)

The same unhelpful notification is shown when attempting to unsubmit a submission for whom the grader has no authorisation for,

![HTTP response 400 unsubmit](https://user-images.githubusercontent.com/44989315/63635802-79f66e80-c699-11e9-99c1-f53250cd8aed.png)

### Reproduction steps

1. Attempt to submit a grading on a student's submission which is not finalised, i.e. `submissionStatus` is `:attempting`

### Development environment
Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

Last updated 24 Aug 2019, 06:00PM

**Comment by Aulud** [comment]
@geshuming Have notified @jiachen247 regarding this oddity. In the meantime, would it be better if we explicitly catch the error codes 400 and 405 and display a custom message in `handleResponseError`?

**Comment by angelsl** [comment]
This is probably because the production backend is behind CloudFront, which serves HTTP 2, which no longer sends a reason phrase.

But anyway, even in HTTP 1.1, the reason phrase is optional:

```
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
Reason-Phrase  = *<TEXT, excluding CR, LF>
```

&mdash; [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html#sec6.1.1)

**Comment by angelsl** [comment]
Not a bug.
