### ISSUE TITLE
Default chapter should be configurable

### ISSUE THREAD

**Issue by martin-henz** [source-academy/cadet#496]
...without re-deploying the frontend. So perhaps there could be some sort of admin interface that let us control such things:

* default chapter
* user management
* group management
* extraction of plagiarism reports (perhaps)
* contest voting management (perhaps)

**Comment by jiachen247** [comment]
CLI tool perhaps?

**Comment by geshuming** [comment]
I would suggest that the playground chapter/library options just be saved locally (along with the other fields such as the editor value. This way we don't even need to manually configure the default chapter.

**Comment by jiachen247** [comment]
If im not wrong thats already the case! default source level only comes into play if it cant find the config in local storage!
