### ISSUE TITLE
Specification for a 4th user role

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#54]
From today's meeting, there needs to be one more role value for the graduate student. Overall, there will be 4 roles, corresponding to:

1. Site administrators, which corresponds to the module's two professors. Site administrators should be able to access all assessments
2. Graduate students, who are responsible for manual marking of assessments. Graduate students should be able to access only assessments belonging to students assigned to them
3. Avengers/TAs, who will be able to access only assessments belonging to their studio group
4. Students

Implementation-wise, it is possible to give graduate students an identical 'role' value as avengers/TAs. The difference being only the students they are assigned---graduate students are assigned (associated) all the students they are responsible for grading, and avengers/TAs are assigned (associated) the students in their studio group. 

More importantly, we need to take note that **the information about these groupings will come from IVLE groups**. Therefore, a process of parsing IVLE 'group' information into the backend database, as well as a way to update these relationships (as in, to update per fixed amount of time, or on student login, or on graduate student/avenger login) should be implemented.

**Comment by indocomsoft** [comment]
So we are sure that all of them has an associated IVLE account, correct?

Since we removed email+password authentication method in #48

**Comment by ningyuansg** [comment]
Yep, if they do not have IVLE accounts already we can just sign them up with guest accounts.

**Comment by martin-henz** [comment]
I think we solved this one by giving every Avenger the right to grade every mission. Seemed to work. Any objections to this?

**Comment by indocomsoft** [comment]
For now, I guess this is resolved pending the refactoring of the authorization system.

One thing to note about allowing all avengers to grade: Without implementation of pagination, retrieving all submissions could be very huge. Last semester, in the 2nd half of the semester, this data could easily reach >4MB, I think at the end of the semester it reached 6MB. It's definitely too huge.

**Comment by martin-henz** [comment]
Yes, will see if the GRADING team can take a look at the pagination issue.
