### ISSUE TITLE
API Documentation (Public)

### ISSUE THREAD

**Issue by tjtanjin** [source-academy/cadet#541]
Hello, I am unable to find any mention of a public API for source backend that allows interested students to experiment with without setting up their own server, obtaining luminus_api_key etc. Would it be possible to provide a public API? It would be of great help in some of the mini projects I wish to do. Thank You!

**Comment by geshuming** [comment]
Are you working on a project on frontend or backend? For front-end you can develop without an active backend api

**Comment by tjtanjin** [comment]
> Are you working on a project on frontend or backend? For front-end you can develop without an active backend api

I am playing around with a [telegram bot](https://github.com/tjtanjin/telesourcebot) that can take in source code and return the output. It's currently done rather ineffectively because the code is manually inserted into the playground for execution. I was hoping there is a public API that I can use instead especially since it was announced that source is likely to revamp its frontend. Thank you for your help!

**Comment by jiachen247** [comment]
check out running jsslang on the cli bro

**Comment by martin-henz** [comment]
> check out running jsslang on the cli bro

But a telegram bot would require server support, right?

The current Source Academy runs all programs (playground and missions) in the client, using js-slang, except the automated grading. For that, we use AWS Lambda.

The problem for your use case: There is no API yet for running Source programs on the server.

You could design such an API and implement it using JS-slang and Node.js.

**Comment by geshuming** [comment]
@tjtanjin You can look up eval bots, since that is what you seem to be doing. You may only require https://github.com/source-academy/js-slang to run Source.

**Comment by tjtanjin** [comment]
Thank you for all the pointers and suggestions! I'll look them up!
