### ISSUE TITLE
Whitelist XML files in Game Dev page

### ISSUE THREAD

**Issue by jetkan-yk** [source-academy/cadet#593]
The Game Dev page serves as a collaborative workspace for story editors to work on the story XML drafts. However, submission of XML files at the upload box is blacklisted by the backend. It should allow the editors to upload & download story XML files.

Basic sanity check on the XML files should be done for security concerns. See:
https://stackoverflow.com/questions/8728672/from-security-perspective-what-should-i-do-when-allowing-users-to-upload-files

**Comment by jetkan-yk** [comment]
This issue is somewhat related to #539 as they currently share the same AWS bucket.

**Comment by angelsl** [comment]
This is now irrelevant since we're implementing a separate stories endpoint.
