### ISSUE TITLE
Implement GradingController

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#67]

**Comment by remo5000** [comment]
Already an issue here, so I'll just comment for your reference.

Can the fields be expanded to include more information?
- Submission ID
- Assessment ID
- Assessment Name
- Assessment Category
- Student ID
- Student Name
- Current XP
- Maximum XP

Do feel free to suggest any improvements or representations, thanks!

**Comment by remo5000** [comment]
@indocomsoft Sorry for the bother, I realised that Grading does not have an `id` (which is submissionId I guess). Is it supposed to have one? Because `Assessment` comes with an `id` as well.

**Comment by indocomsoft** [comment]
Nah, internally it's represented as a submissionId.

Btw I'm removing graded boolean since we're doing autograding @remo5000

**Comment by remo5000** [comment]
Ah right. There's still going to be some field for auto-grading information right?

**Comment by indocomsoft** [comment]
@remo5000 yeah, auto-grader will update the `xp` field.
