### ISSUE TITLE
Act on announcements fetched by Updater

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#79]

**Comment by martin-henz** [comment]
I guess we abandoned the announcement feature. Do we need it, or is IVLE goodenough?

**Comment by indocomsoft** [comment]
IVLE is being deprecated next year. Luminus haven't released any API yet, but if need be, I have written a library in elixir that can retrieve announcements from LumiNUS. https://github.com/indocomsoft/fluminus

I would say this is not really a priority.

**Comment by jiachen247** [comment]
Annocements have been deprecated in favour of a new notification panel + IVLE is soon to be no more.

**Comment by angelsl** [comment]
We've removed announcements.
