### ISSUE TITLE
Add 'has_attempted' to assessments API

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/cadet#84]
@sreycodes:

We need some way to decide which story act in the game to show the user. These correspond to the files in the repository cs1101s/cs1101s at ./stories. At frontend, the logic we will be implementing is:

1. Are all assessments attempted? Then spawn the open-world spaceship
2. If not, spawn the story act of the unattempted assessment with the lowest assessment id.

For your reference, the corresponding files in source-academy/source-academy2 of this functionality:

[`game.html.eex`](https://github.com/source-academy/source-academy2/blob/11466e86facfdcb3527731af0e914baa1da845ef/lib/source_academy_web/templates/page/game.html.eex#L12)
```erb
<%= link "Attempt",
      id: "attempt",
      style: "display:none",
      method: "put",
      to: assessment_path(@conn, :attempt, @assessment_id) %>
<div id="game-display"
     class="sa-game"
     data-story="<%= @story_override || @story %>"
     data-attempted-all="<%= @attempted_all %>"
     data-username="<%= @username %>">
</div>
```

[`page_controller.ex`](https://github.com/source-academy/source-academy2/blob/11466e86facfdcb3527731af0e914baa1da845ef/lib/source_academy_web/controllers/page_controller.ex#L20)
```elixir
  def game(conn, params) do
    user = conn.assigns.current_user
    student = conn.assigns.current_student
    assessment = Assessments.prepare_game(student)
    story_override =
      if Accounts.staff?(user) do
        Map.get(params, "s") || nil
      else
        nil
      end
    if assessment == nil do
      render conn, "game.html",
        assessment_id: -1,
        story: "spaceship",
        username: student.user.first_name,
        story_override: story_override,
        attempted_all: true
    else
      render conn, "game.html",
        assessment_id: assessment.id,
        story: Assessments.story_name(assessment),
        username: student.user.first_name,
        story_override: story_override,
        attempted_all: false
    end
  end
```

[`assessments.ex`](https://github.com/source-academy/source-academy2/blob/11466e86facfdcb3527731af0e914baa1da845ef/lib/source_academy/assessments.ex#L642)
```elixir
  def prepare_game(student) do
    # Get all non-attempted assessment
    assessments = Repo.all(
      from a in Assessment,
        left_join: s in Submission,
          on: a.id == s.assessment_id and s.student_id == ^student.id,
        where: is_nil(s.student_id),
        select: a
    )
    # Filter those can be attempted, min by order, mission first
    assessments =
      assessments
      |> Enum.filter(&(&1.type != :path && can_attempt?(&1, student.user)))
    if Enum.empty?(assessments) do
      nil
    else
      [hd | _ ] = Enum.sort_by(assessments,
        &story_name_pair/1,
        &compare_story_name_pair/2)
      hd
    end
  end

  def story_name_pair(assessment) do
    {assessment.type, assessment.name}
  end

  def compare_story_name_pair({t1, n1}, {t2, n2}) do
    cond do
      t1 == t2 -> n1 <= n2
      t1 == :mission -> true
      t1 == :sidequest && t2 == :mission -> false
      t1 == :contest && t2 == :mission -> false
      t1 == :contest && t2 == :sidequest -> false
      true -> false
    end
  end

  def story_name(assessment) do
    type = Atom.to_string(assessment.type)
    String.downcase(type) <> "-" <> assessment.name
  end
```

**Comment by ningyuansg** [comment]
The has_attempted flag for each assessment can be a check for if a user has ever sent a program to the backend to be 'saved'.

**Comment by sreycodes** [comment]
I wanted to clarify what type of flag are you exactly asking for:

1. In the case when all assessments are attempted, their submission status will be submitted
2. In the case when not, do you want to open the story act of the assessment he/she is currently working on (i.e. the assessment with the status "attempting") or the next assessment that is to be attempted?

**Comment by ningyuansg** [comment]
There are at least two problems that I am aiming to solve with this issue. Below, I am referring to the API specs at master commit 896abe5. **To summaries, we don't necessarily need a literal flag property on assessments to indicate what has been attempted or not, but we do need an easy way to distinguish between what has been attempted or not.**

1. In last sprint's meeting, we decided that there would be no _'submission'_ of assessments. 
    - Students would be able to _save_ their answers to the questions onto the backend database, but there would be no feature to 'commit' a saved answer as the final answer to be graded. 
    - Rather, grading takes place automatically after the deadline of the assessment has passed (and saving further answers beyond this point is, of course, not allowed).
    - Therefore, **there is no way for the student to visually distinguish what assessment they have 'done'.**
    - This is messy, and an inconvenience to the student. They would want to keep track of what they have tried and what they have not tried.
2. What story act to load for the game (refer to `bitbuket:cs1101s/cs1101s/stories`) should depend on a student's progress in the assessments.
    - For example, if two assessments are released at once, if we do not track attempted/unattempted, we can only show one of the two stories
    - Furthermore, all 450 students would have to be shown the same story act. **Individually, we have no information on which to decide what story act to show a student.**

The solution I'm proposing is to add a new route (`assessments/new`, or something) of response `array<AssessmentOverview>` containing assessments that the student has **not yet** attempted/done.
- To determine if an assessment has been attempted/done, we can check if an answer has been saved for that assessment. Implementation is up to you, however.
- Still, there is no way to distinguish between 'attempted' (has tried), or 'done' (student has confirmed answer), but that's fine. 

Then, using this information, we solve the above two problems as such:
1. Assessments in the array of not yet attempted/done assessments are rendered with special visual effects to indicate they are new, unattempted assessments.
2. The story act corresponding to the assessment in the array of not yet attempted/done assessments with the earliest open_at time is shown. If none, show the open-world spaceship.

Alternatively, instead of creating a new route for `array<AssessmentOverview>` of assessments not yet attempted/done, we can:
- Add a boolean field (flag) to each assessment in the already existing model AssessmentsList

**Comment by ningyuansg** [comment]
Sorry about the essay, I tried to shorten it as much as possible

**Comment by ningyuansg** [comment]
(sorry for the essay)

**Comment by martin-henz** [comment]
I agree with Ning Yuan: attempted/done distinction not important for the stories. As long as a student has tried an assessment, he/she should be able to move to the next one, see the next story etc.

**Comment by sreycodes** [comment]
Okay understood. I think I can check all the submissions of a user and see which assessment they belong to and return an array of unattempted assessments.
